# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Dono' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dono

  pod 'PasscodeLock', '~> 1.0'
  pod 'Dodo', '~> 2.2'
  pod 'DonoCore', :git => "https://github.com/dono-app/dono-pod/"
  pod 'IQKeyboardManagerSwift', '~> 4.0'
  pod 'MCSwipeTableViewCell', '~> 2.1'
  pod 'SWRevealViewController', '~> 2.3'
  pod 'SwiftKeychainWrapper', '~> 1.0'
  pod 'CGLMail', '~> 0.1'

target 'DonoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DonoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
